### ISSUE TITLE
More information on failed tests?

### ISSUE THREAD

**Issue by haw230** [okken/pytest-expect#1]
Is there a way to print more information on failed tests? I am comparing two functions and I wish to print out a comparison of the results of both. I am currently using pytest which does print where the ```assert()``` went wrong, but it seems ```assert_expectations()``` does not support it even with the verbose flag. Thank you.

**Comment by okken** [comment]
This is a proof of concept project.
It has been extended to include local variables, which can help if you store the results as local variables before the comparison, with a branched project, https://github.com/astraw38/pytest-assume

In order to do something closer to what assert rewriting does in pytest, we would have to extend pytest with this feature, as the rewriting mechanism currently doesn't have hooks for extra rewrite rules.
